### ISSUE TITLE
Just for info: the custom templates should be under "bootstrap3" for v7 server

### ISSUE THREAD

**Issue by davecapper** [qld-gov-au/formio#63]
We found when trying to override the default templates with this approach that the templates weren't being applied correctly on the Form IO server portal. It turns out that the v7 portal is using "bootstrap3" as the default, so you need to register the templates under "bootstrap3" rather than "bootstrap". vnext (v8) defaults to "bootstrap", so they worked perfectly in there. We've taken the approach to register them under both so it works either way.

**Comment by murraybauer** [comment]
FYI @duttonw @devonpis something we came across, if applicable.

**Comment by devonpis** [comment]
so far we didn't come across problem in the portal which related to register template to `bootstrap` in custom component. but it's a good idea to register both `bootstrap` and `bootstrap3` as a precaution, i'll have a look into that
